title: "HCA Wrangler Docs"
site_url: https://ebi-ait.github.io/hca-ebi-wrangler-central/
remote_theme: pmarsceill/just-the-docs
# remote_theme: leakyabstractions/pretty-docs
search_enabled: true
aux_links:
  "Edit these Docs on GitHub":
    - "//github.com/ebi-ait/hca-ebi-wrangler-central/tree/master/docs"
markdown: kramdown

footer_content: "These docs are a work in progress, help us improve by <a href=\"https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/new/choose\">Making a ticket.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/ebi-ait/hca-ebi-wrangler-central" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
